export const TOGGLE_NAV_DRAWER = 'TOGGLE_NAV_DRAWER';
export const TOGGLE_LOGIN_DIALOG = 'TOGGLE_LOGIN_DIALOG';
export const TOGGLE_REGISTER_DIALOG = 'TOGGLE_REGISTER_DIALOG';
export const SUBMIT_REGISTER = 'SUBMIT_REGISTER';
export const SET_USER_DATA = 'SET_USER_DATA';